web:
  build: .
  ports:
   - "8080:8080"
  links:
    - fake-intel
  command: ./run.sh
  volumes:
    - .:/usr/src/app

fake-intel:
  image: quii/mockingjay-server:1.2
  volumes:
    - ./fakes:/fakes
  command: -config=/fakes/fake-intel.yaml
  ports:
   - "9090:9090"
